from dbfpy import dbf

## create empty DBF, set fields

path_occupancy=r'C:\UBG_to_CEA\baseline\inputs\building-properties\occupancy.dbf'

db = dbf.Dbf(path_occupancy, new=True)

db.addField(
    ("NAME", "C", 15),
("FLOOR_1","C",15),
("FLOOR_2","C",15),
("FLOOR_3","C",15),
("FLOOR_4","C",15),
("FLOOR_5","C",15),
("FLOOR_6","C",15),
("FLOOR_7","C",15),
("FLOOR_8","C",15),
("FLOOR_9","C",15),
("FLOOR_10","C",15),
("FLOOR_11","C",15),
("FLOOR_12","C",15),
("FLOOR_13","C",15),
("FLOOR_14","C",15),
("FLOOR_15","C",15),
("FLOOR_16","C",15),
("FLOOR_17","C",15),
("FLOOR_18","C",15),
("FLOOR_19","C",15)
)

## fill DBF with some records

for name, FLOOR_1, FLOOR_2, FLOOR_3, FLOOR_4, FLOOR_5, FLOOR_6, FLOOR_7, FLOOR_8, FLOOR_9, FLOOR_10, FLOOR_11, FLOOR_12, FLOOR_13, FLOOR_14, FLOOR_15, FLOOR_16, FLOOR_17, FLOOR_18, FLOOR_19 in (
("Bldg_0","OFFICE","OFFICE","COMMERCIAL","OFFICE","COMMERCIAL","OFFICE","RESIDENTIAL","RESIDENTIAL","COMMERCIAL","OFFICE","OFFICE"," "," "," "," "," "," "," "," " ), ("Bldg_1","OFFICE","OFFICE","OFFICE","COMMERCIAL","OFFICE","RESIDENTIAL","OFFICE","COMMERCIAL","OFFICE","OFFICE","OFFICE","OFFICE"," "," "," "," "," "," "," " ), ("Bldg_2","RESIDENTIAL","COMMERCIAL","RESIDENTIAL","RESIDENTIAL","RESIDENTIAL","OFFICE","COMMERCIAL","OFFICE","RESIDENTIAL","RESIDENTIAL","OFFICE","RESIDENTIAL"," "," "," "," "," "," "," " ), ("Bldg_3","RESIDENTIAL","OFFICE","OFFICE","RESIDENTIAL","OFFICE","COMMERCIAL","COMMERCIAL","RESIDENTIAL","COMMERCIAL","OFFICE","RESIDENTIAL"," "," "," "," "," "," "," "," " ), ("Bldg_4","OFFICE","RESIDENTIAL","RESIDENTIAL","OFFICE","RESIDENTIAL","OFFICE","RESIDENTIAL","RESIDENTIAL","OFFICE","COMMERCIAL","OFFICE","OFFICE"," "," "," "," "," "," "," " ), ("Bldg_5","COMMERCIAL","OFFICE","RESIDENTIAL","OFFICE","COMMERCIAL","OFFICE","OFFICE","COMMERCIAL","OFFICE","OFFICE","OFFICE","COMMERCIAL","RESIDENTIAL"," "," "," "," "," "," " ), ("Bldg_6","COMMERCIAL","RESIDENTIAL","RESIDENTIAL","RESIDENTIAL","RESIDENTIAL","RESIDENTIAL","OFFICE","RESIDENTIAL","RESIDENTIAL","RESIDENTIAL","OFFICE","RESIDENTIAL","OFFICE","OFFICE"," "," "," "," "," " ), ("Bldg_7","OFFICE","RESIDENTIAL","OFFICE","OFFICE","COMMERCIAL","OFFICE","OFFICE","RESIDENTIAL","COMMERCIAL","OFFICE","RESIDENTIAL","OFFICE","OFFICE","RESIDENTIAL"," "," "," "," "," " ), ("Bldg_8","OFFICE","OFFICE","RESIDENTIAL","COMMERCIAL","COMMERCIAL","OFFICE","RESIDENTIAL","OFFICE","OFFICE","RESIDENTIAL","RESIDENTIAL","RESIDENTIAL","RESIDENTIAL"," "," "," "," "," "," " ), ("Bldg_9","COMMERCIAL","RESIDENTIAL","OFFICE","RESIDENTIAL","OFFICE","COMMERCIAL","RESIDENTIAL","OFFICE","RESIDENTIAL","OFFICE","OFFICE","RESIDENTIAL"," "," "," "," "," "," "," " ), ("Bldg_10","OFFICE","OFFICE","OFFICE","COMMERCIAL","OFFICE","RESIDENTIAL","RESIDENTIAL","RESIDENTIAL","OFFICE","RESIDENTIAL","OFFICE"," "," "," "," "," "," "," "," " ), ("Bldg_11","OFFICE","OFFICE","OFFICE","RESIDENTIAL","OFFICE","RESIDENTIAL","OFFICE","RESIDENTIAL","OFFICE","RESIDENTIAL","COMMERCIAL","COMMERCIAL","RESIDENTIAL"," "," "," "," "," "," " ), ("Bldg_12","COMMERCIAL","RESIDENTIAL","OFFICE","RESIDENTIAL","OFFICE","OFFICE","OFFICE","OFFICE","COMMERCIAL","OFFICE","COMMERCIAL","OFFICE","OFFICE","OFFICE","OFFICE","OFFICE"," "," "," " ), ("Bldg_13","RESIDENTIAL","RESIDENTIAL","OFFICE","RESIDENTIAL","OFFICE","COMMERCIAL","OFFICE","RESIDENTIAL","OFFICE","OFFICE","OFFICE","OFFICE","OFFICE","RESIDENTIAL","OFFICE","RESIDENTIAL","RESIDENTIAL"," "," " ), ("Bldg_14","OFFICE","OFFICE","RESIDENTIAL","COMMERCIAL","RESIDENTIAL","RESIDENTIAL","OFFICE","RESIDENTIAL","RESIDENTIAL","OFFICE","OFFICE","COMMERCIAL","RESIDENTIAL","COMMERCIAL","OFFICE","OFFICE","OFFICE"," "," " ), ("Bldg_15","RESIDENTIAL","OFFICE","OFFICE","RESIDENTIAL","OFFICE","RESIDENTIAL","RESIDENTIAL","RESIDENTIAL","COMMERCIAL","OFFICE","OFFICE","OFFICE","RESIDENTIAL","RESIDENTIAL","RESIDENTIAL","OFFICE"," "," "," " ), ("Bldg_16","OFFICE","OFFICE","COMMERCIAL","OFFICE","OFFICE","OFFICE","OFFICE","RESIDENTIAL","OFFICE","COMMERCIAL","RESIDENTIAL","COMMERCIAL","RESIDENTIAL"," "," "," "," "," "," " ), ("Bldg_17","OFFICE","OFFICE","RESIDENTIAL","RESIDENTIAL","RESIDENTIAL","OFFICE","COMMERCIAL","RESIDENTIAL","COMMERCIAL","RESIDENTIAL","COMMERCIAL"," "," "," "," "," "," "," "," " ), ("Bldg_18","RESIDENTIAL","OFFICE","OFFICE","RESIDENTIAL","OFFICE","RESIDENTIAL","RESIDENTIAL","COMMERCIAL","OFFICE","RESIDENTIAL","OFFICE","RESIDENTIAL"," "," "," "," "," "," "," " ), ("Bldg_19","COMMERCIAL","RESIDENTIAL","RESIDENTIAL","RESIDENTIAL","COMMERCIAL","RESIDENTIAL","COMMERCIAL","OFFICE","RESIDENTIAL","RESIDENTIAL","OFFICE","OFFICE","COMMERCIAL","OFFICE"," "," "," "," "," " ), ("Bldg_20","OFFICE","COMMERCIAL","RESIDENTIAL","OFFICE","RESIDENTIAL","OFFICE","RESIDENTIAL","OFFICE","COMMERCIAL","RESIDENTIAL","OFFICE","OFFICE","RESIDENTIAL","RESIDENTIAL","OFFICE","OFFICE","OFFICE"," "," " ), ("Bldg_21","COMMERCIAL","RESIDENTIAL","OFFICE","RESIDENTIAL","OFFICE","COMMERCIAL","OFFICE","RESIDENTIAL","COMMERCIAL","COMMERCIAL","OFFICE","RESIDENTIAL","RESIDENTIAL","RESIDENTIAL","RESIDENTIAL","RESIDENTIAL","OFFICE","COMMERCIAL","COMMERCIAL" ), ("Bldg_22","COMMERCIAL","OFFICE","COMMERCIAL","RESIDENTIAL","RESIDENTIAL","OFFICE","RESIDENTIAL","OFFICE","RESIDENTIAL","RESIDENTIAL","OFFICE","OFFICE","RESIDENTIAL","RESIDENTIAL","OFFICE","RESIDENTIAL","COMMERCIAL","RESIDENTIAL","RESIDENTIAL" ), ("Bldg_23","OFFICE","RESIDENTIAL","OFFICE","OFFICE","RESIDENTIAL","OFFICE","OFFICE","OFFICE","RESIDENTIAL","OFFICE","COMMERCIAL","RESIDENTIAL","OFFICE","RESIDENTIAL","OFFICE","COMMERCIAL","OFFICE"," "," " ), ("Bldg_24","OFFICE","OFFICE","OFFICE","RESIDENTIAL","RESIDENTIAL","OFFICE","COMMERCIAL","RESIDENTIAL","COMMERCIAL","OFFICE","OFFICE","OFFICE","RESIDENTIAL","RESIDENTIAL"," "," "," "," "," " ), ("Bldg_25","RESIDENTIAL","RESIDENTIAL","OFFICE","COMMERCIAL","RESIDENTIAL","OFFICE","RESIDENTIAL","OFFICE","RESIDENTIAL","RESIDENTIAL","OFFICE","RESIDENTIAL"," "," "," "," "," "," "," " ), ("Bldg_26","OFFICE","COMMERCIAL","OFFICE","OFFICE","RESIDENTIAL","RESIDENTIAL","RESIDENTIAL","OFFICE","COMMERCIAL","RESIDENTIAL","COMMERCIAL","OFFICE"," "," "," "," "," "," "," " ), ("Bldg_27","RESIDENTIAL","OFFICE","RESIDENTIAL","RESIDENTIAL","RESIDENTIAL","RESIDENTIAL","OFFICE","OFFICE","COMMERCIAL","RESIDENTIAL","RESIDENTIAL","RESIDENTIAL","RESIDENTIAL","COMMERCIAL"," "," "," "," "," " ), ("Bldg_28","RESIDENTIAL","RESIDENTIAL","COMMERCIAL","RESIDENTIAL","COMMERCIAL","OFFICE","RESIDENTIAL","COMMERCIAL","OFFICE","COMMERCIAL","RESIDENTIAL","OFFICE","OFFICE","OFFICE","RESIDENTIAL","OFFICE","RESIDENTIAL"," "," " ), ("Bldg_29","RESIDENTIAL","RESIDENTIAL","RESIDENTIAL","COMMERCIAL","RESIDENTIAL","OFFICE","COMMERCIAL","RESIDENTIAL","RESIDENTIAL","RESIDENTIAL","RESIDENTIAL","COMMERCIAL","OFFICE","OFFICE","OFFICE","RESIDENTIAL","OFFICE","OFFICE","OFFICE" ), ("Bldg_30","OFFICE","RESIDENTIAL","RESIDENTIAL","OFFICE","RESIDENTIAL","RESIDENTIAL","COMMERCIAL","OFFICE","RESIDENTIAL","COMMERCIAL","OFFICE","RESIDENTIAL","OFFICE","OFFICE","OFFICE","OFFICE","COMMERCIAL","COMMERCIAL","COMMERCIAL" ), ("Bldg_31","RESIDENTIAL","OFFICE","RESIDENTIAL","OFFICE","OFFICE","OFFICE","RESIDENTIAL","OFFICE","RESIDENTIAL","RESIDENTIAL","RESIDENTIAL","OFFICE","RESIDENTIAL","COMMERCIAL","RESIDENTIAL","COMMERCIAL","OFFICE"," "," " ), ("Bldg_32","COMMERCIAL","OFFICE","COMMERCIAL","OFFICE","COMMERCIAL","RESIDENTIAL","COMMERCIAL","OFFICE","OFFICE","RESIDENTIAL","RESIDENTIAL","RESIDENTIAL","RESIDENTIAL","RESIDENTIAL"," "," "," "," "," " ), ("Bldg_33","RESIDENTIAL","RESIDENTIAL","RESIDENTIAL","RESIDENTIAL","RESIDENTIAL","OFFICE","COMMERCIAL","OFFICE","OFFICE","RESIDENTIAL","OFFICE","OFFICE"," "," "," "," "," "," "," " ), ("Bldg_34","OFFICE","OFFICE","OFFICE","RESIDENTIAL","OFFICE","COMMERCIAL","OFFICE","OFFICE","RESIDENTIAL","OFFICE","RESIDENTIAL"," "," "," "," "," "," "," "," " ), ("Bldg_35","RESIDENTIAL","RESIDENTIAL","OFFICE","OFFICE","RESIDENTIAL","OFFICE","OFFICE","RESIDENTIAL","RESIDENTIAL","OFFICE","RESIDENTIAL","RESIDENTIAL","OFFICE"," "," "," "," "," "," " ), ("Bldg_36","OFFICE","RESIDENTIAL","OFFICE","RESIDENTIAL","COMMERCIAL","OFFICE","RESIDENTIAL","COMMERCIAL","RESIDENTIAL","OFFICE","OFFICE","OFFICE","RESIDENTIAL","RESIDENTIAL","OFFICE","OFFICE"," "," "," " ), ("Bldg_37","COMMERCIAL","RESIDENTIAL","OFFICE","OFFICE","OFFICE","COMMERCIAL","OFFICE","COMMERCIAL","COMMERCIAL","OFFICE","OFFICE","RESIDENTIAL","RESIDENTIAL","OFFICE","RESIDENTIAL","COMMERCIAL","COMMERCIAL"," "," " ), ("Bldg_38","OFFICE","COMMERCIAL","RESIDENTIAL","RESIDENTIAL","OFFICE","RESIDENTIAL","RESIDENTIAL","OFFICE","COMMERCIAL","OFFICE","OFFICE","COMMERCIAL","OFFICE","COMMERCIAL","COMMERCIAL","COMMERCIAL","OFFICE"," "," " ), ("Bldg_39","RESIDENTIAL","OFFICE","RESIDENTIAL","OFFICE","OFFICE","RESIDENTIAL","OFFICE","COMMERCIAL","COMMERCIAL","RESIDENTIAL","RESIDENTIAL","RESIDENTIAL","OFFICE","COMMERCIAL","RESIDENTIAL","OFFICE"," "," "," " ), ("Bldg_40","COMMERCIAL","COMMERCIAL","RESIDENTIAL","COMMERCIAL","RESIDENTIAL","OFFICE","OFFICE","OFFICE","OFFICE","COMMERCIAL","RESIDENTIAL","RESIDENTIAL","RESIDENTIAL"," "," "," "," "," "," " ), ("Bldg_41","RESIDENTIAL","COMMERCIAL","RESIDENTIAL","OFFICE","OFFICE","COMMERCIAL","COMMERCIAL","RESIDENTIAL","RESIDENTIAL","RESIDENTIAL","RESIDENTIAL"," "," "," "," "," "," "," "," " ), ("Bldg_42","RESIDENTIAL","OFFICE","RESIDENTIAL","OFFICE","RESIDENTIAL","COMMERCIAL","RESIDENTIAL","RESIDENTIAL","RESIDENTIAL","OFFICE","RESIDENTIAL","COMMERCIAL"," "," "," "," "," "," "," " ), ("Bldg_43","OFFICE","RESIDENTIAL","OFFICE","RESIDENTIAL","RESIDENTIAL","OFFICE","OFFICE","RESIDENTIAL","RESIDENTIAL","RESIDENTIAL","RESIDENTIAL","COMMERCIAL","RESIDENTIAL"," "," "," "," "," "," " ), ("Bldg_44","COMMERCIAL","COMMERCIAL","COMMERCIAL","OFFICE","RESIDENTIAL","COMMERCIAL","RESIDENTIAL","OFFICE","RESIDENTIAL","RESIDENTIAL","RESIDENTIAL","OFFICE","RESIDENTIAL","OFFICE"," "," "," "," "," " ), ("Bldg_45","OFFICE","COMMERCIAL","RESIDENTIAL","OFFICE","OFFICE","RESIDENTIAL","COMMERCIAL","COMMERCIAL","OFFICE","RESIDENTIAL","COMMERCIAL","COMMERCIAL","OFFICE","OFFICE"," "," "," "," "," " ), ("Bldg_46","RESIDENTIAL","OFFICE","RESIDENTIAL","COMMERCIAL","RESIDENTIAL","RESIDENTIAL","RESIDENTIAL","RESIDENTIAL","RESIDENTIAL","COMMERCIAL","RESIDENTIAL","OFFICE","OFFICE"," "," "," "," "," "," " ), ("Bldg_47","RESIDENTIAL","RESIDENTIAL","RESIDENTIAL","OFFICE","RESIDENTIAL","RESIDENTIAL","OFFICE","OFFICE","RESIDENTIAL","OFFICE","OFFICE","RESIDENTIAL"," "," "," "," "," "," "," " ), ("Bldg_48","RESIDENTIAL","RESIDENTIAL","OFFICE","OFFICE","OFFICE","OFFICE","RESIDENTIAL","OFFICE","OFFICE","RESIDENTIAL","OFFICE"," "," "," "," "," "," "," "," " ), ("Bldg_49","RESIDENTIAL","OFFICE","COMMERCIAL","COMMERCIAL","COMMERCIAL","RESIDENTIAL","RESIDENTIAL","RESIDENTIAL","RESIDENTIAL","OFFICE","RESIDENTIAL","COMMERCIAL"," "," "," "," "," "," "," " ), ("Bldg_50","OFFICE","OFFICE","OFFICE","OFFICE","RESIDENTIAL","COMMERCIAL","COMMERCIAL","COMMERCIAL","COMMERCIAL","OFFICE","OFFICE","RESIDENTIAL"," "," "," "," "," "," "," " ), ("Bldg_51","RESIDENTIAL","OFFICE","OFFICE","OFFICE","OFFICE","RESIDENTIAL","RESIDENTIAL","COMMERCIAL","RESIDENTIAL","COMMERCIAL","RESIDENTIAL"," "," "," "," "," "," "," "," " )

):
    rec = db.newRecord()
    rec["NAME"] = name
    rec["FLOOR_1"] = FLOOR_1
    rec["FLOOR_2"] = FLOOR_2
    rec["FLOOR_3"] = FLOOR_3
    rec["FLOOR_4"] = FLOOR_4
    rec["FLOOR_5"] = FLOOR_5
    rec["FLOOR_6"] = FLOOR_6
    rec["FLOOR_7"] = FLOOR_7
    rec["FLOOR_8"] = FLOOR_8
    rec["FLOOR_9"] = FLOOR_9
    rec["FLOOR_10"] = FLOOR_10
    rec["FLOOR_11"] = FLOOR_11
    rec["FLOOR_12"] = FLOOR_12
    rec["FLOOR_13"] = FLOOR_13
    rec["FLOOR_14"] = FLOOR_14
    rec["FLOOR_15"] = FLOOR_15
    rec["FLOOR_16"] = FLOOR_16
    rec["FLOOR_17"] = FLOOR_17
    rec["FLOOR_18"] = FLOOR_18
    rec["FLOOR_19"] = FLOOR_19

    rec.store()
db.close()
