name: Bug Report
description: Report a problem to help us improve CEA
title: "[Bug]: "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this issue! Please fill in the sections below to help us fix it faster.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the problem you encountered
      placeholder: |
        Example: "I got an error when running the demand calculation"
    validations:
      required: true

  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How can we reproduce this?
      description: What steps did you take before seeing this problem?
      placeholder: |
        1. I opened CEA Dashboard
        2. I ran the demand calculation for my scenario
        3. I saw this error message: ...
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true

  - type: input
    id: cea-version
    attributes:
      label: CEA Version
      placeholder: e.g., 3.39.2
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional information (optional)
      description: Screenshots, error messages, or anything else that might help
      placeholder: You can drag and drop images or paste error messages here
