@ECHO OFF
CALL %CEA_CONDA_PATH% activate %CEA_CONDA_ENV%
IF %ERRORLEVEL% NEQ 0 EXIT %ERRORLEVEL%
CALL %*
IF %ERRORLEVEL% NEQ 0 EXIT %ERRORLEVEL%
CALL %CEA_CONDA_PATH% deactivate
IF %ERRORLEVEL% NEQ 0 EXIT %ERRORLEVEL%