# Type stub file for cea.config
# Auto-generated from default.config - do not edit manually

from __future__ import annotations

from typing import Any, Dict, List, Union, Optional, Generator, Tuple, overload, Literal
import configparser

# Module-level constants
CEA_CONFIG: str
DEFAULT_CONFIG: str

class Configuration:
    # Core configuration attributes
    default_config: configparser.ConfigParser
    user_config: configparser.ConfigParser
    sections: Dict[str, Section]
    restricted_to: Optional[List[str]]

    # Known sections from default.config with typed section classes
    general: GeneralSection
    database_helper: DatabaseHelperSection
    archetypes_mapper: ArchetypesMapperSection
    streets_helper: StreetsHelperSection
    terrain_helper: TerrainHelperSection
    surroundings_helper: SurroundingsHelperSection
    zone_helper: ZoneHelperSection
    trees_helper: TreesHelperSection
    weather_helper: WeatherHelperSection
    radiation_crax: RadiationCraxSection
    radiation: RadiationSection
    radiation_simplified: RadiationSimplifiedSection
    occupancy: OccupancySection
    demand: DemandSection
    final_energy: FinalEnergySection
    solar_technology: SolarTechnologySection
    what_ifs: WhatIfsSection
    emissions: EmissionsSection
    create_new_pathway: CreateNewPathwaySection
    pathway_intervention_templates_define: PathwayInterventionTemplatesDefineSection
    pathway_events_apply_templates: PathwayEventsApplyTemplatesSection
    bake_pathway_states: BakePathwayStatesSection
    pathway_simulations: PathwaySimulationsSection
    pathway_state_edit: PathwayStateEditSection
    pathway_state_workflow: PathwayStateWorkflowSection
    extract_reference_case: ExtractReferenceCaseSection
    solar: SolarSection
    dbf_tools: DbfToolsSection
    to_rhino_gh: ToRhinoGhSection
    from_rhino_gh: FromRhinoGhSection
    shapefile_tools: ShapefileToolsSection
    sensitivity_analysis_tools: SensitivityAnalysisToolsSection
    format_helper: FormatHelperSection
    batch_process_workflow: BatchProcessWorkflowSection
    result_summary: ResultSummarySection
    result_analytics: ResultAnalyticsSection
    test: TestSection
    trace_inputlocator: TraceInputlocatorSection
    thermal_network: ThermalNetworkSection
    thermal_network_simplified: ThermalNetworkSimplifiedSection
    thermal_network_detailed: ThermalNetworkDetailedSection
    thermal_network_phasing: ThermalNetworkPhasingSection
    thermal_network_optimization: ThermalNetworkOptimizationSection
    optimization: OptimizationSection
    optimization_new: OptimizationNewSection
    plots: PlotsSection
    plots_optimization: PlotsOptimizationSection
    plots_supply_system: PlotsSupplySystemSection
    plots_comparisons: PlotsComparisonsSection
    sewage: SewageSection
    water_body: WaterBodySection
    shallow_geothermal: ShallowGeothermalSection
    create_new_scenario: CreateNewScenarioSection
    decentralized: DecentralizedSection
    network_layout: NetworkLayoutSection
    multi_criteria: MultiCriteriaSection
    workflow: WorkflowSection
    rename_building: RenameBuildingSection
    create_mixed_use_type: CreateMixedUseTypeSection
    create_polygon: CreatePolygonSection
    server: ServerSection
    schemas: SchemasSection
    development: DevelopmentSection
    plots_include_plants_buildings: PlotsIncludePlantsBuildingsSection
    plots_general: PlotsGeneralSection
    plots_building_filter: PlotsBuildingFilterSection
    plots_demand: PlotsDemandSection
    plots_final_energy: PlotsFinalEnergySection
    plots_heat_rejection: PlotsHeatRejectionSection
    plots_lifecycle_emissions: PlotsLifecycleEmissionsSection
    plots_operational_emissions: PlotsOperationalEmissionsSection
    plots_emission_timeline: PlotsEmissionTimelineSection
    plots_pathway_emission_timeline: PlotsPathwayEmissionTimelineSection
    plots_solar: PlotsSolarSection
    plots_cost_breakdown: PlotsCostBreakdownSection
    plots_cost_sankey: PlotsCostSankeySection
    plots_energy_sankey: PlotsEnergySankeySection
    plots_ldc_component: PlotsLdcComponentSection

    # Common general section parameters (frequently accessed)
    project: str
    scenario_name: str
    scenario: str
    multiprocessing: bool
    number_of_cpus_to_keep_free: int
    debug: bool
    plugins: List[Any]

    # Nested classes
    class RestrictionContextManager:
        config: Any
        parameters: Optional[List[str]]
        def __enter__(self) -> 'RestrictionContextManager': ...  # noqa: F821
        def __exit__(self, exc_type, exc_val, exc_tb) -> None: ...
        def __init__(self, config, parameters: Optional[List[str]]) -> None: ...
        def apply(self) -> None: ...
        def clear(self) -> None: ...

    # Overloads for specific section access
    @overload
    def __getattr__(self, item: Literal["general"]) -> GeneralSection: ...
    @overload
    def __getattr__(self, item: Literal["database_helper"]) -> DatabaseHelperSection: ...
    @overload
    def __getattr__(self, item: Literal["archetypes_mapper"]) -> ArchetypesMapperSection: ...
    @overload
    def __getattr__(self, item: Literal["streets_helper"]) -> StreetsHelperSection: ...
    @overload
    def __getattr__(self, item: Literal["terrain_helper"]) -> TerrainHelperSection: ...
    @overload
    def __getattr__(self, item: Literal["surroundings_helper"]) -> SurroundingsHelperSection: ...
    @overload
    def __getattr__(self, item: Literal["zone_helper"]) -> ZoneHelperSection: ...
    @overload
    def __getattr__(self, item: Literal["trees_helper"]) -> TreesHelperSection: ...
    @overload
    def __getattr__(self, item: Literal["weather_helper"]) -> WeatherHelperSection: ...
    @overload
    def __getattr__(self, item: Literal["radiation_crax"]) -> RadiationCraxSection: ...
    @overload
    def __getattr__(self, item: Literal["radiation"]) -> RadiationSection: ...
    @overload
    def __getattr__(self, item: Literal["radiation_simplified"]) -> RadiationSimplifiedSection: ...
    @overload
    def __getattr__(self, item: Literal["occupancy"]) -> OccupancySection: ...
    @overload
    def __getattr__(self, item: Literal["demand"]) -> DemandSection: ...
    @overload
    def __getattr__(self, item: Literal["final_energy"]) -> FinalEnergySection: ...
    @overload
    def __getattr__(self, item: Literal["solar_technology"]) -> SolarTechnologySection: ...
    @overload
    def __getattr__(self, item: Literal["what_ifs"]) -> WhatIfsSection: ...
    @overload
    def __getattr__(self, item: Literal["emissions"]) -> EmissionsSection: ...
    @overload
    def __getattr__(self, item: Literal["create_new_pathway"]) -> CreateNewPathwaySection: ...
    @overload
    def __getattr__(self, item: Literal["pathway_intervention_templates_define"]) -> PathwayInterventionTemplatesDefineSection: ...
    @overload
    def __getattr__(self, item: Literal["pathway_events_apply_templates"]) -> PathwayEventsApplyTemplatesSection: ...
    @overload
    def __getattr__(self, item: Literal["bake_pathway_states"]) -> BakePathwayStatesSection: ...
    @overload
    def __getattr__(self, item: Literal["pathway_simulations"]) -> PathwaySimulationsSection: ...
    @overload
    def __getattr__(self, item: Literal["pathway_state_edit"]) -> PathwayStateEditSection: ...
    @overload
    def __getattr__(self, item: Literal["pathway_state_workflow"]) -> PathwayStateWorkflowSection: ...
    @overload
    def __getattr__(self, item: Literal["extract_reference_case"]) -> ExtractReferenceCaseSection: ...
    @overload
    def __getattr__(self, item: Literal["solar"]) -> SolarSection: ...
    @overload
    def __getattr__(self, item: Literal["dbf_tools"]) -> DbfToolsSection: ...
    @overload
    def __getattr__(self, item: Literal["to_rhino_gh"]) -> ToRhinoGhSection: ...
    @overload
    def __getattr__(self, item: Literal["from_rhino_gh"]) -> FromRhinoGhSection: ...
    @overload
    def __getattr__(self, item: Literal["shapefile_tools"]) -> ShapefileToolsSection: ...
    @overload
    def __getattr__(self, item: Literal["sensitivity_analysis_tools"]) -> SensitivityAnalysisToolsSection: ...
    @overload
    def __getattr__(self, item: Literal["format_helper"]) -> FormatHelperSection: ...
    @overload
    def __getattr__(self, item: Literal["batch_process_workflow"]) -> BatchProcessWorkflowSection: ...
    @overload
    def __getattr__(self, item: Literal["result_summary"]) -> ResultSummarySection: ...
    @overload
    def __getattr__(self, item: Literal["result_analytics"]) -> ResultAnalyticsSection: ...
    @overload
    def __getattr__(self, item: Literal["test"]) -> TestSection: ...
    @overload
    def __getattr__(self, item: Literal["trace_inputlocator"]) -> TraceInputlocatorSection: ...
    @overload
    def __getattr__(self, item: Literal["thermal_network"]) -> ThermalNetworkSection: ...
    @overload
    def __getattr__(self, item: Literal["thermal_network_simplified"]) -> ThermalNetworkSimplifiedSection: ...
    @overload
    def __getattr__(self, item: Literal["thermal_network_detailed"]) -> ThermalNetworkDetailedSection: ...
    @overload
    def __getattr__(self, item: Literal["thermal_network_phasing"]) -> ThermalNetworkPhasingSection: ...
    @overload
    def __getattr__(self, item: Literal["thermal_network_optimization"]) -> ThermalNetworkOptimizationSection: ...
    @overload
    def __getattr__(self, item: Literal["optimization"]) -> OptimizationSection: ...
    @overload
    def __getattr__(self, item: Literal["optimization_new"]) -> OptimizationNewSection: ...
    @overload
    def __getattr__(self, item: Literal["plots"]) -> PlotsSection: ...
    @overload
    def __getattr__(self, item: Literal["plots_optimization"]) -> PlotsOptimizationSection: ...
    @overload
    def __getattr__(self, item: Literal["plots_supply_system"]) -> PlotsSupplySystemSection: ...
    @overload
    def __getattr__(self, item: Literal["plots_comparisons"]) -> PlotsComparisonsSection: ...
    @overload
    def __getattr__(self, item: Literal["sewage"]) -> SewageSection: ...
    @overload
    def __getattr__(self, item: Literal["water_body"]) -> WaterBodySection: ...
    @overload
    def __getattr__(self, item: Literal["shallow_geothermal"]) -> ShallowGeothermalSection: ...
    @overload
    def __getattr__(self, item: Literal["create_new_scenario"]) -> CreateNewScenarioSection: ...
    @overload
    def __getattr__(self, item: Literal["decentralized"]) -> DecentralizedSection: ...
    @overload
    def __getattr__(self, item: Literal["network_layout"]) -> NetworkLayoutSection: ...
    @overload
    def __getattr__(self, item: Literal["multi_criteria"]) -> MultiCriteriaSection: ...
    @overload
    def __getattr__(self, item: Literal["workflow"]) -> WorkflowSection: ...
    @overload
    def __getattr__(self, item: Literal["rename_building"]) -> RenameBuildingSection: ...
    @overload
    def __getattr__(self, item: Literal["create_mixed_use_type"]) -> CreateMixedUseTypeSection: ...
    @overload
    def __getattr__(self, item: Literal["create_polygon"]) -> CreatePolygonSection: ...
    @overload
    def __getattr__(self, item: Literal["server"]) -> ServerSection: ...
    @overload
    def __getattr__(self, item: Literal["schemas"]) -> SchemasSection: ...
    @overload
    def __getattr__(self, item: Literal["development"]) -> DevelopmentSection: ...
    @overload
    def __getattr__(self, item: Literal["plots_include_plants_buildings"]) -> PlotsIncludePlantsBuildingsSection: ...
    @overload
    def __getattr__(self, item: Literal["plots_general"]) -> PlotsGeneralSection: ...
    @overload
    def __getattr__(self, item: Literal["plots_building_filter"]) -> PlotsBuildingFilterSection: ...
    @overload
    def __getattr__(self, item: Literal["plots_demand"]) -> PlotsDemandSection: ...
    @overload
    def __getattr__(self, item: Literal["plots_final_energy"]) -> PlotsFinalEnergySection: ...
    @overload
    def __getattr__(self, item: Literal["plots_heat_rejection"]) -> PlotsHeatRejectionSection: ...
    @overload
    def __getattr__(self, item: Literal["plots_lifecycle_emissions"]) -> PlotsLifecycleEmissionsSection: ...
    @overload
    def __getattr__(self, item: Literal["plots_operational_emissions"]) -> PlotsOperationalEmissionsSection: ...
    @overload
    def __getattr__(self, item: Literal["plots_emission_timeline"]) -> PlotsEmissionTimelineSection: ...
    @overload
    def __getattr__(self, item: Literal["plots_pathway_emission_timeline"]) -> PlotsPathwayEmissionTimelineSection: ...
    @overload
    def __getattr__(self, item: Literal["plots_solar"]) -> PlotsSolarSection: ...
    @overload
    def __getattr__(self, item: Literal["plots_cost_breakdown"]) -> PlotsCostBreakdownSection: ...
    @overload
    def __getattr__(self, item: Literal["plots_cost_sankey"]) -> PlotsCostSankeySection: ...
    @overload
    def __getattr__(self, item: Literal["plots_energy_sankey"]) -> PlotsEnergySankeySection: ...
    @overload
    def __getattr__(self, item: Literal["plots_ldc_component"]) -> PlotsLdcComponentSection: ...

    # Overloads for general section parameter access
    @overload
    def __getattr__(self, item: Literal["project"]) -> str: ...
    @overload
    def __getattr__(self, item: Literal["scenario_name"]) -> str: ...
    @overload
    def __getattr__(self, item: Literal["scenario"]) -> str: ...
    @overload
    def __getattr__(self, item: Literal["multiprocessing"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["number_of_cpus_to_keep_free"]) -> int: ...
    @overload
    def __getattr__(self, item: Literal["debug"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["plugins"]) -> List[Any]: ...

    def __getattr__(self, item: str) -> Union['Section', Any]: ...

    def __init__(self, config_file: str = ...) -> None: ...
    def __setattr__(self, key: str, value: Any) -> None: ...
    def apply_command_line_args(self, args: List[str], option_list: List[str]) -> None: ...
    def get(self, fqname: str) -> Any: ...
    def get_number_of_processes(self) -> int: ...
    def get_parameter(self, fqname: str) -> Parameter: ...
    def ignore_restrictions(self) -> RestrictionContextManager: ...
    def matching_parameters(self, option_list: List[str]) -> Generator[Tuple[Section, Parameter]]: ...
    def refresh_plugins(self) -> None: ...
    def restrict_to(self, option_list: List[str]) -> None: ...
    def save(self, config_file: str = ...) -> None: ...
    def temp_restrictions(self, parameters: List[str]) -> RestrictionContextManager: ...

class Section:
    name: str
    config: Configuration
    parameters: Dict[str, Parameter]

    def __getattr__(self, item: str) -> Any: ...
    def __init__(self, name: str, config: 'Configuration') -> None: ...
    def __repr__(self) -> str: ...
    def __setattr__(self, key: str, value: Any) -> None: ...

# Typed section classes with parameter annotations
class GeneralSection(Section):
    """Typed section for general configuration"""
    project: str
    scenario_name: str
    scenario: str
    multiprocessing: bool
    number_of_cpus_to_keep_free: int
    debug: bool
    plugins: List[Any]

    @overload
    def __getattr__(self, item: Literal["project"]) -> str: ...
    @overload
    def __getattr__(self, item: Literal["scenario_name"]) -> str: ...
    @overload
    def __getattr__(self, item: Literal["scenario"]) -> str: ...
    @overload
    def __getattr__(self, item: Literal["multiprocessing"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["number_of_cpus_to_keep_free"]) -> int: ...
    @overload
    def __getattr__(self, item: Literal["debug"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["plugins"]) -> List[Any]: ...
    def __getattr__(self, item: str) -> Any: ...

class DatabaseHelperSection(Section):
    """Typed section for database-helper configuration"""
    databases_path: str
    databases: list[str]

    @overload
    def __getattr__(self, item: Literal["databases_path"]) -> str: ...
    @overload
    def __getattr__(self, item: Literal["databases"]) -> list[str]: ...
    def __getattr__(self, item: str) -> Any: ...

class ArchetypesMapperSection(Section):
    """Typed section for archetypes-mapper configuration"""
    input_databases: list[str]
    buildings: list[str]

    @overload
    def __getattr__(self, item: Literal["input_databases"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["buildings"]) -> list[str]: ...
    def __getattr__(self, item: str) -> Any: ...

class StreetsHelperSection(Section):
    """Typed section for streets-helper configuration"""
    include_private_streets: bool

    def __getattr__(self, item: str) -> Any: ...

class TerrainHelperSection(Section):
    """Typed section for terrain-helper configuration"""
    grid_size: int
    buffer: float

    @overload
    def __getattr__(self, item: Literal["grid_size"]) -> int: ...
    @overload
    def __getattr__(self, item: Literal["buffer"]) -> float: ...
    def __getattr__(self, item: str) -> Any: ...

class SurroundingsHelperSection(Section):
    """Typed section for surroundings-helper configuration"""
    buffer: float

    def __getattr__(self, item: str) -> Any: ...

class ZoneHelperSection(Section):
    """Typed section for zone-helper configuration"""
    height_ag: float | None
    floors_ag: int | None
    year_construction: int | None
    height_bg: float
    floors_bg: int
    occupancy_type: Optional[str]
    include_building_parts: bool
    fix_overlapping_geometries: bool

    @overload
    def __getattr__(self, item: Literal["height_ag"]) -> float | None: ...
    @overload
    def __getattr__(self, item: Literal["floors_ag"]) -> int | None: ...
    @overload
    def __getattr__(self, item: Literal["year_construction"]) -> int | None: ...
    @overload
    def __getattr__(self, item: Literal["height_bg"]) -> float: ...
    @overload
    def __getattr__(self, item: Literal["floors_bg"]) -> int: ...
    @overload
    def __getattr__(self, item: Literal["occupancy_type"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["include_building_parts"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["fix_overlapping_geometries"]) -> bool: ...
    def __getattr__(self, item: str) -> Any: ...

class TreesHelperSection(Section):
    """Typed section for trees-helper configuration"""
    trees: str | None

    def __getattr__(self, item: str) -> Any: ...

class WeatherHelperSection(Section):
    """Typed section for weather-helper configuration"""
    weather: str
    year: int
    climate_pathway: Optional[str]
    percentile: Optional[str]
    variables: list[str]

    @overload
    def __getattr__(self, item: Literal["weather"]) -> str: ...
    @overload
    def __getattr__(self, item: Literal["year"]) -> int: ...
    @overload
    def __getattr__(self, item: Literal["climate_pathway"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["percentile"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["variables"]) -> list[str]: ...
    def __getattr__(self, item: str) -> Any: ...

class RadiationCraxSection(Section):
    """Typed section for radiation-crax configuration"""
    buildings: list[str]
    albedo: float
    calculate_sensor_data: bool
    using_cea_sensor: bool
    roof_grid: float
    walls_grid: float
    mesh_clipping_view_factor: bool
    zone_geometry: float
    surrounding_geometry: float
    neglect_adjacent_buildings: bool
    neighbor_filter_altitude_angle: float
    update_shadow_day: float

    @overload
    def __getattr__(self, item: Literal["buildings"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["albedo"]) -> float: ...
    @overload
    def __getattr__(self, item: Literal["calculate_sensor_data"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["using_cea_sensor"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["roof_grid"]) -> float: ...
    @overload
    def __getattr__(self, item: Literal["walls_grid"]) -> float: ...
    @overload
    def __getattr__(self, item: Literal["mesh_clipping_view_factor"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["zone_geometry"]) -> float: ...
    @overload
    def __getattr__(self, item: Literal["surrounding_geometry"]) -> float: ...
    @overload
    def __getattr__(self, item: Literal["neglect_adjacent_buildings"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["neighbor_filter_altitude_angle"]) -> float: ...
    @overload
    def __getattr__(self, item: Literal["update_shadow_day"]) -> float: ...
    def __getattr__(self, item: str) -> Any: ...

class RadiationSection(Section):
    """Typed section for radiation configuration"""
    buildings: list[str]
    roof_grid: float
    walls_grid: float
    zone_geometry: float
    surrounding_geometry: float
    consider_floors: bool
    neglect_adjacent_buildings: bool
    albedo: float
    rad_ab: int
    rad_ad: int
    rad_as: int
    rad_ar: int
    rad_aa: float
    rad_lr: int
    rad_st: float
    rad_sj: float
    rad_lw: float
    rad_dj: float
    rad_ds: float
    rad_dr: int
    rad_dp: int
    n_buildings_in_chunk: int
    write_sensor_data: bool

    @overload
    def __getattr__(self, item: Literal["buildings"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["roof_grid"]) -> float: ...
    @overload
    def __getattr__(self, item: Literal["walls_grid"]) -> float: ...
    @overload
    def __getattr__(self, item: Literal["zone_geometry"]) -> float: ...
    @overload
    def __getattr__(self, item: Literal["surrounding_geometry"]) -> float: ...
    @overload
    def __getattr__(self, item: Literal["consider_floors"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["neglect_adjacent_buildings"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["albedo"]) -> float: ...
    @overload
    def __getattr__(self, item: Literal["rad_ab"]) -> int: ...
    @overload
    def __getattr__(self, item: Literal["rad_ad"]) -> int: ...
    @overload
    def __getattr__(self, item: Literal["rad_as"]) -> int: ...
    @overload
    def __getattr__(self, item: Literal["rad_ar"]) -> int: ...
    @overload
    def __getattr__(self, item: Literal["rad_aa"]) -> float: ...
    @overload
    def __getattr__(self, item: Literal["rad_lr"]) -> int: ...
    @overload
    def __getattr__(self, item: Literal["rad_st"]) -> float: ...
    @overload
    def __getattr__(self, item: Literal["rad_sj"]) -> float: ...
    @overload
    def __getattr__(self, item: Literal["rad_lw"]) -> float: ...
    @overload
    def __getattr__(self, item: Literal["rad_dj"]) -> float: ...
    @overload
    def __getattr__(self, item: Literal["rad_ds"]) -> float: ...
    @overload
    def __getattr__(self, item: Literal["rad_dr"]) -> int: ...
    @overload
    def __getattr__(self, item: Literal["rad_dp"]) -> int: ...
    @overload
    def __getattr__(self, item: Literal["n_buildings_in_chunk"]) -> int: ...
    @overload
    def __getattr__(self, item: Literal["write_sensor_data"]) -> bool: ...
    def __getattr__(self, item: str) -> Any: ...

class RadiationSimplifiedSection(Section):
    """Typed section for radiation-simplified configuration"""
    sample_buildings: list[str]
    buffer: float

    @overload
    def __getattr__(self, item: Literal["sample_buildings"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["buffer"]) -> float: ...
    def __getattr__(self, item: str) -> Any: ...

class OccupancySection(Section):
    """Typed section for occupancy configuration"""
    occupancy_model: Optional[str]
    buildings: list[str]

    @overload
    def __getattr__(self, item: Literal["occupancy_model"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["buildings"]) -> list[str]: ...
    def __getattr__(self, item: str) -> Any: ...

class DemandSection(Section):
    """Typed section for demand configuration"""
    buildings: list[str]
    use_dynamic_infiltration_calculation: bool
    overheating_warning: bool
    retain_technical_results: bool

    @overload
    def __getattr__(self, item: Literal["buildings"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["use_dynamic_infiltration_calculation"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["overheating_warning"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["retain_technical_results"]) -> bool: ...
    def __getattr__(self, item: str) -> Any: ...

class FinalEnergySection(Section):
    """Typed section for final-energy configuration"""
    overwrite_supply_settings: bool
    what_if_name: str
    network_name: str | None
    dhw_booster_type_building: str | None
    hs_booster_type_building: str | None
    supply_type_cs_building: str | None
    supply_type_cs_district: str | None
    supply_type_hs_building: str | None
    supply_type_hs_district: str | None
    supply_type_dhw_building: str | None
    supply_type_dhw_district: str | None

    @overload
    def __getattr__(self, item: Literal["overwrite_supply_settings"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["what_if_name"]) -> str: ...
    @overload
    def __getattr__(self, item: Literal["network_name"]) -> str | None: ...
    @overload
    def __getattr__(self, item: Literal["dhw_booster_type_building"]) -> str | None: ...
    @overload
    def __getattr__(self, item: Literal["hs_booster_type_building"]) -> str | None: ...
    @overload
    def __getattr__(self, item: Literal["supply_type_cs_building"]) -> str | None: ...
    @overload
    def __getattr__(self, item: Literal["supply_type_cs_district"]) -> str | None: ...
    @overload
    def __getattr__(self, item: Literal["supply_type_hs_building"]) -> str | None: ...
    @overload
    def __getattr__(self, item: Literal["supply_type_hs_district"]) -> str | None: ...
    @overload
    def __getattr__(self, item: Literal["supply_type_dhw_building"]) -> str | None: ...
    @overload
    def __getattr__(self, item: Literal["supply_type_dhw_district"]) -> str | None: ...
    def __getattr__(self, item: str) -> Any: ...

class SolarTechnologySection(Section):
    """Typed section for solar-technology configuration"""
    buildings: list[str]
    panels_on_roof: str | None
    panels_on_wall_north: str | None
    panels_on_wall_south: str | None
    panels_on_wall_east: str | None
    panels_on_wall_west: str | None

    @overload
    def __getattr__(self, item: Literal["buildings"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["panels_on_roof"]) -> str | None: ...
    @overload
    def __getattr__(self, item: Literal["panels_on_wall_north"]) -> str | None: ...
    @overload
    def __getattr__(self, item: Literal["panels_on_wall_south"]) -> str | None: ...
    @overload
    def __getattr__(self, item: Literal["panels_on_wall_east"]) -> str | None: ...
    @overload
    def __getattr__(self, item: Literal["panels_on_wall_west"]) -> str | None: ...
    def __getattr__(self, item: str) -> Any: ...

class WhatIfsSection(Section):
    """Typed section for what-ifs configuration"""
    what_if_name: list[str]

    def __getattr__(self, item: str) -> Any: ...

class EmissionsSection(Section):
    """Typed section for emissions configuration"""
    what_if_name: list[str]
    year_end: int | None
    grid_carbon_intensity_dataset_csv: str | None
    csv_carbon_intensity_column_name: Any
    grid_decarbonise_reference_year: int | None
    grid_decarbonise_target_year: int | None
    grid_decarbonise_target_emission_factor: float | None

    @overload
    def __getattr__(self, item: Literal["what_if_name"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["year_end"]) -> int | None: ...
    @overload
    def __getattr__(self, item: Literal["grid_carbon_intensity_dataset_csv"]) -> str | None: ...
    @overload
    def __getattr__(self, item: Literal["csv_carbon_intensity_column_name"]) -> Any: ...
    @overload
    def __getattr__(self, item: Literal["grid_decarbonise_reference_year"]) -> int | None: ...
    @overload
    def __getattr__(self, item: Literal["grid_decarbonise_target_year"]) -> int | None: ...
    @overload
    def __getattr__(self, item: Literal["grid_decarbonise_target_emission_factor"]) -> float | None: ...
    def __getattr__(self, item: str) -> Any: ...

class CreateNewPathwaySection(Section):
    """Typed section for create-new-pathway configuration"""
    new_pathway_name: Any

    def __getattr__(self, item: str) -> Any: ...

class PathwayInterventionTemplatesDefineSection(Section):
    """Typed section for pathway-intervention-templates-define configuration"""
    intervention_template_name: Any
    intervention_template_description: Any
    archetypes: str
    wall_material_name_1: str | None
    wall_thickness_1_m: float | None
    wall_material_name_2: str | None
    wall_thickness_2_m: float | None
    wall_material_name_3: str | None
    wall_thickness_3_m: float | None
    wall_lifetime: int | None
    roof_material_name_1: str | None
    roof_thickness_1_m: float | None
    roof_material_name_2: str | None
    roof_thickness_2_m: float | None
    roof_material_name_3: str | None
    roof_thickness_3_m: float | None
    roof_lifetime: int | None
    floor_material_name_1: str | None
    floor_thickness_1_m: float | None
    floor_material_name_2: str | None
    floor_thickness_2_m: float | None
    floor_material_name_3: str | None
    floor_thickness_3_m: float | None
    floor_lifetime: int | None
    base_material_name_1: str | None
    base_thickness_1_m: float | None
    base_material_name_2: str | None
    base_thickness_2_m: float | None
    base_material_name_3: str | None
    base_thickness_3_m: float | None
    base_lifetime: int | None
    type_win: str | None
    supply_type_hs: str | None
    supply_type_cs: str | None
    supply_type_dhw: str | None
    supply_type_el: str | None
    hvac_type_hs: str | None
    hvac_type_cs: str | None
    hvac_type_dhw: str | None
    hvac_type_ctrl: str | None
    hvac_type_vent: str | None

    @overload
    def __getattr__(self, item: Literal["existing_pathway_name"]) -> str: ...
    @overload
    def __getattr__(self, item: Literal["intervention_template_name"]) -> Any: ...
    @overload
    def __getattr__(self, item: Literal["intervention_template_description"]) -> Any: ...
    @overload
    def __getattr__(self, item: Literal["archetypes"]) -> str: ...
    @overload
    def __getattr__(self, item: Literal["wall_material_name_1"]) -> str | None: ...
    @overload
    def __getattr__(self, item: Literal["wall_thickness_1_m"]) -> float | None: ...
    @overload
    def __getattr__(self, item: Literal["wall_material_name_2"]) -> str | None: ...
    @overload
    def __getattr__(self, item: Literal["wall_thickness_2_m"]) -> float | None: ...
    @overload
    def __getattr__(self, item: Literal["wall_material_name_3"]) -> str | None: ...
    @overload
    def __getattr__(self, item: Literal["wall_thickness_3_m"]) -> float | None: ...
    @overload
    def __getattr__(self, item: Literal["wall_lifetime"]) -> int | None: ...
    @overload
    def __getattr__(self, item: Literal["roof_material_name_1"]) -> str | None: ...
    @overload
    def __getattr__(self, item: Literal["roof_thickness_1_m"]) -> float | None: ...
    @overload
    def __getattr__(self, item: Literal["roof_material_name_2"]) -> str | None: ...
    @overload
    def __getattr__(self, item: Literal["roof_thickness_2_m"]) -> float | None: ...
    @overload
    def __getattr__(self, item: Literal["roof_material_name_3"]) -> str | None: ...
    @overload
    def __getattr__(self, item: Literal["roof_thickness_3_m"]) -> float | None: ...
    @overload
    def __getattr__(self, item: Literal["roof_lifetime"]) -> int | None: ...
    @overload
    def __getattr__(self, item: Literal["floor_material_name_1"]) -> str | None: ...
    @overload
    def __getattr__(self, item: Literal["floor_thickness_1_m"]) -> float | None: ...
    @overload
    def __getattr__(self, item: Literal["floor_material_name_2"]) -> str | None: ...
    @overload
    def __getattr__(self, item: Literal["floor_thickness_2_m"]) -> float | None: ...
    @overload
    def __getattr__(self, item: Literal["floor_material_name_3"]) -> str | None: ...
    @overload
    def __getattr__(self, item: Literal["floor_thickness_3_m"]) -> float | None: ...
    @overload
    def __getattr__(self, item: Literal["floor_lifetime"]) -> int | None: ...
    @overload
    def __getattr__(self, item: Literal["base_material_name_1"]) -> str | None: ...
    @overload
    def __getattr__(self, item: Literal["base_thickness_1_m"]) -> float | None: ...
    @overload
    def __getattr__(self, item: Literal["base_material_name_2"]) -> str | None: ...
    @overload
    def __getattr__(self, item: Literal["base_thickness_2_m"]) -> float | None: ...
    @overload
    def __getattr__(self, item: Literal["base_material_name_3"]) -> str | None: ...
    @overload
    def __getattr__(self, item: Literal["base_thickness_3_m"]) -> float | None: ...
    @overload
    def __getattr__(self, item: Literal["base_lifetime"]) -> int | None: ...
    @overload
    def __getattr__(self, item: Literal["type_win"]) -> str | None: ...
    @overload
    def __getattr__(self, item: Literal["supply_type_hs"]) -> str | None: ...
    @overload
    def __getattr__(self, item: Literal["supply_type_cs"]) -> str | None: ...
    @overload
    def __getattr__(self, item: Literal["supply_type_dhw"]) -> str | None: ...
    @overload
    def __getattr__(self, item: Literal["supply_type_el"]) -> str | None: ...
    @overload
    def __getattr__(self, item: Literal["hvac_type_hs"]) -> str | None: ...
    @overload
    def __getattr__(self, item: Literal["hvac_type_cs"]) -> str | None: ...
    @overload
    def __getattr__(self, item: Literal["hvac_type_dhw"]) -> str | None: ...
    @overload
    def __getattr__(self, item: Literal["hvac_type_ctrl"]) -> str | None: ...
    @overload
    def __getattr__(self, item: Literal["hvac_type_vent"]) -> str | None: ...
    def __getattr__(self, item: str) -> Any: ...

class PathwayEventsApplyTemplatesSection(Section):
    """Typed section for pathway-events-apply-templates configuration"""
    existing_pathway_names: List[str]
    year_of_state: int
    intervention_templates: List[str]

    @overload
    def __getattr__(self, item: Literal["existing_pathway_name"]) -> str: ...
    @overload
    def __getattr__(self, item: Literal["year_of_state"]) -> int: ...
    @overload
    def __getattr__(self, item: Literal["intervention_templates"]) -> List[str]: ...
    def __getattr__(self, item: str) -> Any: ...

class BakePathwayStatesSection(Section):
    """Typed section for bake-pathway-states configuration"""
    existing_pathway_name: str

    def __getattr__(self, item: str) -> Any: ...

class PathwaySimulationsSection(Section):
    """Typed section for pathway-simulations configuration"""
    existing_pathway_name: str

    def __getattr__(self, item: str) -> Any: ...

class PathwayStateEditSection(Section):
    """Typed section for pathway-state-edit configuration"""
    existing_pathway_names: list[str]
    year_of_state: int
    buildings_to_construct: list[str]
    buildings_to_demolish: list[str]
    raw_yaml: Any

    @overload
    def __getattr__(self, item: Literal["existing_pathway_name"]) -> str: ...
    @overload
    def __getattr__(self, item: Literal["year_of_state"]) -> int: ...
    @overload
    def __getattr__(self, item: Literal["new_buildings"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["demolished_buildings"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["raw_yaml"]) -> Any: ...
    def __getattr__(self, item: str) -> Any: ...

class PathwayStateWorkflowSection(Section):
    """Typed section for pathway-state-workflow configuration"""
    existing_pathway_name: str

    def __getattr__(self, item: str) -> Any: ...

class ExtractReferenceCaseSection(Section):
    """Typed section for extract-reference-case configuration"""
    destination: str
    case: Optional[str]

    @overload
    def __getattr__(self, item: Literal["destination"]) -> str: ...
    @overload
    def __getattr__(self, item: Literal["case"]) -> Optional[str]: ...
    def __getattr__(self, item: str) -> Any: ...

class SolarSection(Section):
    """Typed section for solar configuration"""
    type_pvpanel: str
    type_scpanel: list[str]
    panel_on_roof: bool
    panel_on_wall: bool
    annual_radiation_threshold: float
    t_in_sc: float | None
    t_in_pvt: float | None
    solar_window_solstice: int
    max_roof_coverage: float
    custom_tilt_angle: bool
    panel_tilt_angle: float
    buildings: list[str]

    @overload
    def __getattr__(self, item: Literal["type_pvpanel"]) -> str: ...
    @overload
    def __getattr__(self, item: Literal["type_scpanel"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["panel_on_roof"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["panel_on_wall"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["annual_radiation_threshold"]) -> float: ...
    @overload
    def __getattr__(self, item: Literal["t_in_sc"]) -> float | None: ...
    @overload
    def __getattr__(self, item: Literal["t_in_pvt"]) -> float | None: ...
    @overload
    def __getattr__(self, item: Literal["solar_window_solstice"]) -> int: ...
    @overload
    def __getattr__(self, item: Literal["max_roof_coverage"]) -> float: ...
    @overload
    def __getattr__(self, item: Literal["custom_tilt_angle"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["panel_tilt_angle"]) -> float: ...
    @overload
    def __getattr__(self, item: Literal["buildings"]) -> list[str]: ...
    def __getattr__(self, item: str) -> Any: ...

class DbfToolsSection(Section):
    """Typed section for dbf-tools configuration"""
    input_file: str | None
    output_file_name: Any
    output_path: str

    @overload
    def __getattr__(self, item: Literal["input_file"]) -> str | None: ...
    @overload
    def __getattr__(self, item: Literal["output_file_name"]) -> Any: ...
    @overload
    def __getattr__(self, item: Literal["output_path"]) -> str: ...
    def __getattr__(self, item: str) -> Any: ...

class ToRhinoGhSection(Section):
    """Typed section for to-rhino-gh configuration"""
    include_zone: bool
    include_site: bool
    include_surroundings: bool
    include_streets: bool
    include_trees: bool
    network_name: str | None

    @overload
    def __getattr__(self, item: Literal["include_zone"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["include_site"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["include_surroundings"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["include_streets"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["include_trees"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["network_name"]) -> str | None: ...
    def __getattr__(self, item: str) -> Any: ...

class FromRhinoGhSection(Section):
    """Typed section for from-rhino-gh configuration"""
    reference_scenario_name: str
    copy_database: bool
    copy_terrain: bool
    copy_weather: bool

    @overload
    def __getattr__(self, item: Literal["reference_scenario_name"]) -> str: ...
    @overload
    def __getattr__(self, item: Literal["copy_database"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["copy_terrain"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["copy_weather"]) -> bool: ...
    def __getattr__(self, item: str) -> Any: ...

class ShapefileToolsSection(Section):
    """Typed section for shapefile-tools configuration"""
    input_file: str | None
    output_file_name: Any
    output_path: str
    reference_crs_file: str | None
    polygon: bool

    @overload
    def __getattr__(self, item: Literal["input_file"]) -> str | None: ...
    @overload
    def __getattr__(self, item: Literal["output_file_name"]) -> Any: ...
    @overload
    def __getattr__(self, item: Literal["output_path"]) -> str: ...
    @overload
    def __getattr__(self, item: Literal["reference_crs_file"]) -> str | None: ...
    @overload
    def __getattr__(self, item: Literal["polygon"]) -> bool: ...
    def __getattr__(self, item: str) -> Any: ...

class SensitivityAnalysisToolsSection(Section):
    """Typed section for sensitivity-analysis-tools configuration"""
    create_scenario_directory: bool
    n: int
    having_variable_1: bool
    variable_1_lower_bound: float | None
    variable_1_upper_bound: float | None
    having_variable_2: bool
    variable_2_lower_bound: float | None
    variable_2_upper_bound: float | None
    having_variable_3: bool
    variable_3_lower_bound: float | None
    variable_3_upper_bound: float | None
    having_variable_4: bool
    variable_4_lower_bound: float | None
    variable_4_upper_bound: float | None
    having_variable_5: bool
    variable_5_lower_bound: float | None
    variable_5_upper_bound: float | None

    @overload
    def __getattr__(self, item: Literal["create_scenario_directory"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["n"]) -> int: ...
    @overload
    def __getattr__(self, item: Literal["having_variable_1"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["variable_1_lower_bound"]) -> float | None: ...
    @overload
    def __getattr__(self, item: Literal["variable_1_upper_bound"]) -> float | None: ...
    @overload
    def __getattr__(self, item: Literal["having_variable_2"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["variable_2_lower_bound"]) -> float | None: ...
    @overload
    def __getattr__(self, item: Literal["variable_2_upper_bound"]) -> float | None: ...
    @overload
    def __getattr__(self, item: Literal["having_variable_3"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["variable_3_lower_bound"]) -> float | None: ...
    @overload
    def __getattr__(self, item: Literal["variable_3_upper_bound"]) -> float | None: ...
    @overload
    def __getattr__(self, item: Literal["having_variable_4"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["variable_4_lower_bound"]) -> float | None: ...
    @overload
    def __getattr__(self, item: Literal["variable_4_upper_bound"]) -> float | None: ...
    @overload
    def __getattr__(self, item: Literal["having_variable_5"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["variable_5_lower_bound"]) -> float | None: ...
    @overload
    def __getattr__(self, item: Literal["variable_5_upper_bound"]) -> float | None: ...
    def __getattr__(self, item: str) -> Any: ...

class FormatHelperSection(Section):
    """Typed section for format-helper configuration"""
    scenarios_to_verify_and_migrate: list[str]
    migrate_from_cea_3: bool

    @overload
    def __getattr__(self, item: Literal["scenarios_to_verify_and_migrate"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["migrate_from_cea_3"]) -> bool: ...
    def __getattr__(self, item: str) -> Any: ...

class BatchProcessWorkflowSection(Section):
    """Typed section for batch-process-workflow configuration"""
    scenarios_to_simulate: list[str]
    export_to_rhino_gh: bool
    import_from_rhino_gh: bool
    database_helper: bool
    archetypes_mapper: bool
    weather_helper: bool
    surroundings_helper: bool
    terrain_helper: bool
    streets_helper: bool
    radiation: bool
    solar_potential_pv: bool
    solar_potential_pvt: bool
    solar_potential_sc: bool
    shallow_geothermal_potential: bool
    water_body_potential: bool
    demand_forecasting: bool
    sewage_heat_potential: bool
    thermal_network_layout: bool
    thermal_network_operation: bool
    emissions: bool
    system_costs: bool
    optimisation: bool
    results_summary_and_analytics: bool

    @overload
    def __getattr__(self, item: Literal["scenarios_to_simulate"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["export_to_rhino_gh"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["import_from_rhino_gh"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["database_helper"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["archetypes_mapper"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["weather_helper"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["surroundings_helper"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["terrain_helper"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["streets_helper"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["radiation"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["solar_potential_pv"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["solar_potential_pvt"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["solar_potential_sc"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["shallow_geothermal_potential"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["water_body_potential"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["demand_forecasting"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["sewage_heat_potential"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["thermal_network_layout"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["thermal_network_operation"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["emissions"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["system_costs"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["optimisation"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["results_summary_and_analytics"]) -> bool: ...
    def __getattr__(self, item: str) -> Any: ...

class ResultSummarySection(Section):
    """Typed section for result-summary configuration"""
    folder_name_to_save_exported_results: Any
    aggregate_by_building: bool
    aggregate_by_time_period: list[str]
    period_start_date: list[str]
    period_end_date: list[str]
    building_energy_demand: bool
    solar_irradiation: bool
    solar_technologies: list[str] | None
    network_name: list[str] | None
    what_if_name_final_energy: list[str] | None
    what_if_name_emissions: list[str] | None
    what_if_name_costs: list[str] | None
    what_if_name_heat_rejection: list[str] | None
    include_advanced_analytics: bool
    use_cea_acronym_format_column_names: bool
    use_conditioned_floor_area_for_normalisation: bool

    @overload
    def __getattr__(self, item: Literal["folder_name_to_save_exported_results"]) -> Any: ...
    @overload
    def __getattr__(self, item: Literal["aggregate_by_building"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["aggregate_by_time_period"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["period_start_date"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["period_end_date"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["building_energy_demand"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["solar_irradiation"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["solar_technologies"]) -> list[str] | None: ...
    @overload
    def __getattr__(self, item: Literal["network_name"]) -> list[str] | None: ...
    @overload
    def __getattr__(self, item: Literal["what_if_name_final_energy"]) -> list[str] | None: ...
    @overload
    def __getattr__(self, item: Literal["what_if_name_emissions"]) -> list[str] | None: ...
    @overload
    def __getattr__(self, item: Literal["what_if_name_costs"]) -> list[str] | None: ...
    @overload
    def __getattr__(self, item: Literal["what_if_name_heat_rejection"]) -> list[str] | None: ...
    @overload
    def __getattr__(self, item: Literal["include_advanced_analytics"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["use_cea_acronym_format_column_names"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["use_conditioned_floor_area_for_normalisation"]) -> bool: ...
    def __getattr__(self, item: str) -> Any: ...

class ResultAnalyticsSection(Section):
    """Typed section for result-analytics configuration"""
    all_scenarios: bool

    def __getattr__(self, item: str) -> Any: ...

class TestSection(Section):
    """Typed section for test configuration"""
    type: Optional[str]

    def __getattr__(self, item: str) -> Any: ...

class TraceInputlocatorSection(Section):
    """Typed section for trace-inputlocator configuration"""
    scripts: list[str]
    meta_output_file: str

    @overload
    def __getattr__(self, item: Literal["scripts"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["meta_output_file"]) -> str: ...
    def __getattr__(self, item: str) -> Any: ...

class ThermalNetworkSection(Section):
    """Typed section for thermal-network configuration"""
    network_name: list[str]
    network_type: list[str]
    dh_temperature_mode: Optional[str]
    network_temperature_dh: float
    network_temperature_dc: float
    equivalent_length_factor: float

    @overload
    def __getattr__(self, item: Literal["network_name"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["network_type"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["dh_temperature_mode"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["network_temperature_dh"]) -> float: ...
    @overload
    def __getattr__(self, item: Literal["network_temperature_dc"]) -> float: ...
    @overload
    def __getattr__(self, item: Literal["equivalent_length_factor"]) -> float: ...
    def __getattr__(self, item: str) -> Any: ...

class ThermalNetworkSimplifiedSection(Section):
    """Typed section for thermal-network-simplified configuration"""
    min_head_substation: float
    hw_friction_coefficient: int
    peak_load_velocity: float
    peak_load_percentage: float
    set_diameter: bool

    @overload
    def __getattr__(self, item: Literal["min_head_substation"]) -> float: ...
    @overload
    def __getattr__(self, item: Literal["hw_friction_coefficient"]) -> int: ...
    @overload
    def __getattr__(self, item: Literal["peak_load_velocity"]) -> float: ...
    @overload
    def __getattr__(self, item: Literal["peak_load_percentage"]) -> float: ...
    @overload
    def __getattr__(self, item: Literal["set_diameter"]) -> bool: ...
    def __getattr__(self, item: str) -> Any: ...

class ThermalNetworkDetailedSection(Section):
    """Typed section for thermal-network-detailed configuration"""
    load_max_edge_flowrate_from_previous_run: bool
    start_t: int
    stop_t: int
    use_representative_week_per_month: bool
    minimum_mass_flow_iteration_limit: int
    minimum_edge_mass_flow: float
    diameter_iteration_limit: int
    substation_cooling_systems: list[str]
    substation_heating_systems: list[str]

    @overload
    def __getattr__(self, item: Literal["load_max_edge_flowrate_from_previous_run"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["start_t"]) -> int: ...
    @overload
    def __getattr__(self, item: Literal["stop_t"]) -> int: ...
    @overload
    def __getattr__(self, item: Literal["use_representative_week_per_month"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["minimum_mass_flow_iteration_limit"]) -> int: ...
    @overload
    def __getattr__(self, item: Literal["minimum_edge_mass_flow"]) -> float: ...
    @overload
    def __getattr__(self, item: Literal["diameter_iteration_limit"]) -> int: ...
    @overload
    def __getattr__(self, item: Literal["substation_cooling_systems"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["substation_heating_systems"]) -> list[str]: ...
    def __getattr__(self, item: str) -> Any: ...

class ThermalNetworkPhasingSection(Section):
    """Typed section for thermal-network-phasing configuration"""
    phasing_plan_name: str
    phase_completion_year: List[str]
    sizing_strategy: Optional[str]
    replacement_cost_multiplier: float

    @overload
    def __getattr__(self, item: Literal["phasing_plan_name"]) -> str: ...
    @overload
    def __getattr__(self, item: Literal["phase_completion_year"]) -> List[str]: ...
    @overload
    def __getattr__(self, item: Literal["sizing_strategy"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["replacement_cost_multiplier"]) -> float: ...
    def __getattr__(self, item: str) -> Any: ...

class ThermalNetworkOptimizationSection(Section):
    """Typed section for thermal-network-optimization configuration"""
    network_type: Optional[str]
    network_names: List[str]
    file_type: Optional[str]
    set_diameter: bool
    load_max_edge_flowrate_from_previous_run: bool
    start_t: int
    stop_t: int
    network_name: Any
    possible_plant_sites: List[str]
    min_number_of_plants: int
    max_number_of_plants: int
    number_of_individuals: int
    chance_of_mutation: float
    number_of_generations: int
    lucky_few: int
    optimize_loop_branch: bool
    optimize_network_loads: bool
    optimize_building_connections: bool
    use_rule_based_approximation: bool
    use_representative_week_per_month: bool
    minimum_mass_flow_iteration_limit: int
    minimum_edge_mass_flow: float
    diameter_iteration_limit: int
    substation_cooling_systems: List[str]
    substation_heating_systems: List[str]
    disconnected_buildings: List[str]
    yearly_cost_calculations: bool

    @overload
    def __getattr__(self, item: Literal["network_type"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["network_names"]) -> List[str]: ...
    @overload
    def __getattr__(self, item: Literal["file_type"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["set_diameter"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["load_max_edge_flowrate_from_previous_run"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["start_t"]) -> int: ...
    @overload
    def __getattr__(self, item: Literal["stop_t"]) -> int: ...
    @overload
    def __getattr__(self, item: Literal["network_name"]) -> Any: ...
    @overload
    def __getattr__(self, item: Literal["possible_plant_sites"]) -> List[str]: ...
    @overload
    def __getattr__(self, item: Literal["min_number_of_plants"]) -> int: ...
    @overload
    def __getattr__(self, item: Literal["max_number_of_plants"]) -> int: ...
    @overload
    def __getattr__(self, item: Literal["number_of_individuals"]) -> int: ...
    @overload
    def __getattr__(self, item: Literal["chance_of_mutation"]) -> float: ...
    @overload
    def __getattr__(self, item: Literal["number_of_generations"]) -> int: ...
    @overload
    def __getattr__(self, item: Literal["lucky_few"]) -> int: ...
    @overload
    def __getattr__(self, item: Literal["optimize_loop_branch"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["optimize_network_loads"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["optimize_building_connections"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["use_rule_based_approximation"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["use_representative_week_per_month"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["minimum_mass_flow_iteration_limit"]) -> int: ...
    @overload
    def __getattr__(self, item: Literal["minimum_edge_mass_flow"]) -> float: ...
    @overload
    def __getattr__(self, item: Literal["diameter_iteration_limit"]) -> int: ...
    @overload
    def __getattr__(self, item: Literal["substation_cooling_systems"]) -> List[str]: ...
    @overload
    def __getattr__(self, item: Literal["substation_heating_systems"]) -> List[str]: ...
    @overload
    def __getattr__(self, item: Literal["disconnected_buildings"]) -> List[str]: ...
    @overload
    def __getattr__(self, item: Literal["yearly_cost_calculations"]) -> bool: ...
    def __getattr__(self, item: str) -> Any: ...

class OptimizationSection(Section):
    """Typed section for optimization configuration"""
    network_type: Optional[str]
    technologies_dh: list[str]
    technologies_dc: list[str]
    objective_functions_dc: list[str]
    cold_storage_type: Optional[str]
    population_size: int | None
    number_of_generations: int
    random_seed: int
    mutation_prob: float
    mutation_method_integer: Optional[str]
    mutation_method_continuous: Optional[str]
    crossover_prob: float
    crossover_method_integer: Optional[str]
    crossover_method_continuous: Optional[str]

    @overload
    def __getattr__(self, item: Literal["network_type"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["technologies_dh"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["technologies_dc"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["objective_functions_dc"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["cold_storage_type"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["population_size"]) -> int | None: ...
    @overload
    def __getattr__(self, item: Literal["number_of_generations"]) -> int: ...
    @overload
    def __getattr__(self, item: Literal["random_seed"]) -> int: ...
    @overload
    def __getattr__(self, item: Literal["mutation_prob"]) -> float: ...
    @overload
    def __getattr__(self, item: Literal["mutation_method_integer"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["mutation_method_continuous"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["crossover_prob"]) -> float: ...
    @overload
    def __getattr__(self, item: Literal["crossover_method_integer"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["crossover_method_continuous"]) -> Optional[str]: ...
    def __getattr__(self, item: str) -> Any: ...

class OptimizationNewSection(Section):
    """Typed section for optimization-new configuration"""
    network_name: str | None
    network_type: Optional[str]
    buildings: list[str]
    cooling_components: list[str]
    heating_components: list[str]
    heat_rejection_components: list[str]
    maximum_number_of_networks: int
    objective_functions: list[str]
    generate_detailed_outputs: bool
    retain_run_results: bool
    available_energy_sources: list[str]
    available_energy_potentials: list[str]
    component_efficiency_model_complexity: Optional[str]
    network_temperature: int
    systems_algorithm: Optional[str]
    systems_mutation_method: Optional[str]
    systems_crossover_method: Optional[str]
    networks_algorithm: Optional[str]
    networks_mutation_method: Optional[str]
    networks_crossover_method: Optional[str]
    building_clustering_method: Optional[str]
    networks_overlap_correction_method: Optional[str]
    ga_population_size: int | None
    ga_number_of_generations: int
    ga_mutation_prob: float
    ga_crossover_prob: float
    ga_mutation_eta: float
    min_head_substation: float
    hw_friction_coefficient: int
    peak_load_velocity: float
    equivalent_length_factor: float
    peak_load_percentage: float
    network_lifetime: float

    @overload
    def __getattr__(self, item: Literal["network_name"]) -> str | None: ...
    @overload
    def __getattr__(self, item: Literal["network_type"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["buildings"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["cooling_components"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["heating_components"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["heat_rejection_components"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["maximum_number_of_networks"]) -> int: ...
    @overload
    def __getattr__(self, item: Literal["objective_functions"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["generate_detailed_outputs"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["retain_run_results"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["available_energy_sources"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["available_energy_potentials"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["component_efficiency_model_complexity"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["network_temperature"]) -> int: ...
    @overload
    def __getattr__(self, item: Literal["systems_algorithm"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["systems_mutation_method"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["systems_crossover_method"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["networks_algorithm"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["networks_mutation_method"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["networks_crossover_method"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["building_clustering_method"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["networks_overlap_correction_method"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["ga_population_size"]) -> int | None: ...
    @overload
    def __getattr__(self, item: Literal["ga_number_of_generations"]) -> int: ...
    @overload
    def __getattr__(self, item: Literal["ga_mutation_prob"]) -> float: ...
    @overload
    def __getattr__(self, item: Literal["ga_crossover_prob"]) -> float: ...
    @overload
    def __getattr__(self, item: Literal["ga_mutation_eta"]) -> float: ...
    @overload
    def __getattr__(self, item: Literal["min_head_substation"]) -> float: ...
    @overload
    def __getattr__(self, item: Literal["hw_friction_coefficient"]) -> int: ...
    @overload
    def __getattr__(self, item: Literal["peak_load_velocity"]) -> float: ...
    @overload
    def __getattr__(self, item: Literal["equivalent_length_factor"]) -> float: ...
    @overload
    def __getattr__(self, item: Literal["peak_load_percentage"]) -> float: ...
    @overload
    def __getattr__(self, item: Literal["network_lifetime"]) -> float: ...
    def __getattr__(self, item: str) -> Any: ...

class PlotsSection(Section):
    """Typed section for plots configuration"""
    buildings: list[str]
    building: Optional[str]
    categories: list[str]
    network_type: Optional[str]
    network_name: Any
    plant_node: str
    timeframe: Optional[str]
    normalization: Optional[str]

    @overload
    def __getattr__(self, item: Literal["buildings"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["building"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["categories"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["network_type"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["network_name"]) -> Any: ...
    @overload
    def __getattr__(self, item: Literal["plant_node"]) -> str: ...
    @overload
    def __getattr__(self, item: Literal["timeframe"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["normalization"]) -> Optional[str]: ...
    def __getattr__(self, item: str) -> Any: ...

class PlotsOptimizationSection(Section):
    """Typed section for plots-optimization configuration"""
    generation: str

    def __getattr__(self, item: str) -> Any: ...

class PlotsSupplySystemSection(Section):
    """Typed section for plots-supply-system configuration"""
    system: Optional[str]

    def __getattr__(self, item: str) -> Any: ...

class PlotsComparisonsSection(Section):
    """Typed section for plots-comparisons configuration"""
    scenarios_and_systems: List[str]

    def __getattr__(self, item: str) -> Any: ...

class SewageSection(Section):
    """Typed section for sewage configuration"""
    heat_exchanger_length: int
    sewage_water_ratio: float | None
    sewage_water_district: float

    @overload
    def __getattr__(self, item: Literal["heat_exchanger_length"]) -> int: ...
    @overload
    def __getattr__(self, item: Literal["sewage_water_ratio"]) -> float | None: ...
    @overload
    def __getattr__(self, item: Literal["sewage_water_district"]) -> float: ...
    def __getattr__(self, item: str) -> Any: ...

class WaterBodySection(Section):
    """Typed section for water-body configuration"""
    max_water_volume_withdrawal: float
    max_delta_temperature_withdrawal: float
    temperature_max: float
    temperature_min: float

    @overload
    def __getattr__(self, item: Literal["max_water_volume_withdrawal"]) -> float: ...
    @overload
    def __getattr__(self, item: Literal["max_delta_temperature_withdrawal"]) -> float: ...
    @overload
    def __getattr__(self, item: Literal["temperature_max"]) -> float: ...
    @overload
    def __getattr__(self, item: Literal["temperature_min"]) -> float: ...
    def __getattr__(self, item: str) -> Any: ...

class ShallowGeothermalSection(Section):
    """Typed section for shallow-geothermal configuration"""
    buildings_available: list[str]
    extra_area_available: float
    average_probe_depth: float

    @overload
    def __getattr__(self, item: Literal["buildings_available"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["extra_area_available"]) -> float: ...
    @overload
    def __getattr__(self, item: Literal["average_probe_depth"]) -> float: ...
    def __getattr__(self, item: str) -> Any: ...

class CreateNewScenarioSection(Section):
    """Typed section for create-new-scenario configuration"""
    project: Any
    scenario: Any
    output_path: str
    zone: str
    terrain: str | None
    streets: str | None
    surroundings: str | None
    typology: str | None

    @overload
    def __getattr__(self, item: Literal["project"]) -> Any: ...
    @overload
    def __getattr__(self, item: Literal["scenario"]) -> Any: ...
    @overload
    def __getattr__(self, item: Literal["output_path"]) -> str: ...
    @overload
    def __getattr__(self, item: Literal["zone"]) -> str: ...
    @overload
    def __getattr__(self, item: Literal["terrain"]) -> str | None: ...
    @overload
    def __getattr__(self, item: Literal["streets"]) -> str | None: ...
    @overload
    def __getattr__(self, item: Literal["surroundings"]) -> str | None: ...
    @overload
    def __getattr__(self, item: Literal["typology"]) -> str | None: ...
    def __getattr__(self, item: str) -> Any: ...

class DecentralizedSection(Section):
    """Typed section for decentralized configuration"""
    pass

class NetworkLayoutSection(Section):
    """Typed section for network-layout configuration"""
    overwrite_supply_settings: bool
    network_name: str
    include_services: list[str]
    cooling_connected_buildings: list[str]
    heating_connected_buildings: list[str]
    cooling_plant_building: Any
    heating_plant_building: Any
    itemised_dh_services: list[str]
    number_of_components: int | None
    existing_network: str | None
    edges_shp_path: str | None
    nodes_shp_path: str | None
    network_geojson_path: str | None
    network_layout_mode: Optional[str]
    auto_modify_network: bool
    consider_only_buildings_with_demand: bool
    algorithm: Optional[str]
    connection_candidates: int
    snap_tolerance: float | None

    @overload
    def __getattr__(self, item: Literal["overwrite_supply_settings"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["network_name"]) -> str: ...
    @overload
    def __getattr__(self, item: Literal["include_services"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["cooling_connected_buildings"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["heating_connected_buildings"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["cooling_plant_building"]) -> Any: ...
    @overload
    def __getattr__(self, item: Literal["heating_plant_building"]) -> Any: ...
    @overload
    def __getattr__(self, item: Literal["itemised_dh_services"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["number_of_components"]) -> int | None: ...
    @overload
    def __getattr__(self, item: Literal["existing_network"]) -> str | None: ...
    @overload
    def __getattr__(self, item: Literal["edges_shp_path"]) -> str | None: ...
    @overload
    def __getattr__(self, item: Literal["nodes_shp_path"]) -> str | None: ...
    @overload
    def __getattr__(self, item: Literal["network_geojson_path"]) -> str | None: ...
    @overload
    def __getattr__(self, item: Literal["network_layout_mode"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["auto_modify_network"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["consider_only_buildings_with_demand"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["algorithm"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["connection_candidates"]) -> int: ...
    @overload
    def __getattr__(self, item: Literal["snap_tolerance"]) -> float | None: ...
    def __getattr__(self, item: str) -> Any: ...

class MultiCriteriaSection(Section):
    """Typed section for multi-criteria configuration"""
    generation: int
    annualized_capital_costs: float
    total_capital_costs: float
    annual_operation_costs: float
    annual_emissions: float

    @overload
    def __getattr__(self, item: Literal["generation"]) -> int: ...
    @overload
    def __getattr__(self, item: Literal["annualized_capital_costs"]) -> float: ...
    @overload
    def __getattr__(self, item: Literal["total_capital_costs"]) -> float: ...
    @overload
    def __getattr__(self, item: Literal["annual_operation_costs"]) -> float: ...
    @overload
    def __getattr__(self, item: Literal["annual_emissions"]) -> float: ...
    def __getattr__(self, item: str) -> Any: ...

class WorkflowSection(Section):
    """Typed section for workflow configuration"""
    workflow: str
    resume: bool
    resume_file: str
    trace_input: bool

    @overload
    def __getattr__(self, item: Literal["workflow"]) -> str: ...
    @overload
    def __getattr__(self, item: Literal["resume"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["resume_file"]) -> str: ...
    @overload
    def __getattr__(self, item: Literal["trace_input"]) -> bool: ...
    def __getattr__(self, item: str) -> Any: ...

class RenameBuildingSection(Section):
    """Typed section for rename-building configuration"""
    old: Optional[str]
    new: Any

    @overload
    def __getattr__(self, item: Literal["old"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["new"]) -> Any: ...
    def __getattr__(self, item: str) -> Any: ...

class CreateMixedUseTypeSection(Section):
    """Typed section for create-mixed-use-type configuration"""
    use_type: Any
    metadata: Any
    ratios: List[str]

    @overload
    def __getattr__(self, item: Literal["use_type"]) -> Any: ...
    @overload
    def __getattr__(self, item: Literal["metadata"]) -> Any: ...
    @overload
    def __getattr__(self, item: Literal["ratios"]) -> List[str]: ...
    def __getattr__(self, item: str) -> Any: ...

class CreatePolygonSection(Section):
    """Typed section for create-polygon configuration"""
    coordinates: List[Tuple[float, float]]
    filename: Any

    @overload
    def __getattr__(self, item: Literal["coordinates"]) -> List[Tuple[float, float]]: ...
    @overload
    def __getattr__(self, item: Literal["filename"]) -> Any: ...
    def __getattr__(self, item: str) -> Any: ...

class ServerSection(Section):
    """Typed section for server configuration"""
    project_root: str
    protocol: Optional[str]
    host: Any
    port: int
    dev: bool

    @overload
    def __getattr__(self, item: Literal["project_root"]) -> str: ...
    @overload
    def __getattr__(self, item: Literal["protocol"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["host"]) -> Any: ...
    @overload
    def __getattr__(self, item: Literal["port"]) -> int: ...
    @overload
    def __getattr__(self, item: Literal["dev"]) -> bool: ...
    def __getattr__(self, item: str) -> Any: ...

class SchemasSection(Section):
    """Typed section for schemas configuration"""
    locator_method: Any
    args: Optional[Any]

    @overload
    def __getattr__(self, item: Literal["locator_method"]) -> Any: ...
    @overload
    def __getattr__(self, item: Literal["args"]) -> Optional[Any]: ...
    def __getattr__(self, item: str) -> Any: ...

class DevelopmentSection(Section):
    """Typed section for development configuration"""
    nsis: Any
    conda: Any
    gui: Any
    yarn: Any
    release_version: Any

    @overload
    def __getattr__(self, item: Literal["nsis"]) -> Any: ...
    @overload
    def __getattr__(self, item: Literal["conda"]) -> Any: ...
    @overload
    def __getattr__(self, item: Literal["gui"]) -> Any: ...
    @overload
    def __getattr__(self, item: Literal["yarn"]) -> Any: ...
    @overload
    def __getattr__(self, item: Literal["release_version"]) -> Any: ...
    def __getattr__(self, item: str) -> Any: ...

class PlotsIncludePlantsBuildingsSection(Section):
    """Typed section for plots-include-plants-buildings configuration"""
    include: list[str]

    def __getattr__(self, item: str) -> Any: ...

class PlotsGeneralSection(Section):
    """Typed section for plots-general configuration"""
    plot_title: Any
    plot_type: Optional[str]
    y_min: float | None
    y_max: float | None
    y_step: float | None
    y_label: Any
    facet_by_numbers_wrapped: int | None
    facet_by_rows: bool
    x_sorted_by: Optional[str]
    x_sorted_reversed: bool
    x_label: Any
    context: dict[str, Any] | None

    @overload
    def __getattr__(self, item: Literal["plot_title"]) -> Any: ...
    @overload
    def __getattr__(self, item: Literal["plot_type"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["y_min"]) -> float | None: ...
    @overload
    def __getattr__(self, item: Literal["y_max"]) -> float | None: ...
    @overload
    def __getattr__(self, item: Literal["y_step"]) -> float | None: ...
    @overload
    def __getattr__(self, item: Literal["y_label"]) -> Any: ...
    @overload
    def __getattr__(self, item: Literal["facet_by_numbers_wrapped"]) -> int | None: ...
    @overload
    def __getattr__(self, item: Literal["facet_by_rows"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["x_sorted_by"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["x_sorted_reversed"]) -> bool: ...
    @overload
    def __getattr__(self, item: Literal["x_label"]) -> Any: ...
    @overload
    def __getattr__(self, item: Literal["context"]) -> dict[str, Any] | None: ...
    def __getattr__(self, item: str) -> Any: ...

class PlotsBuildingFilterSection(Section):
    """Typed section for plots-building-filter configuration"""
    buildings: list[str]
    filter_buildings_by_year_start: int | None
    filter_buildings_by_year_end: int | None
    filter_buildings_by_construction_type: str
    filter_buildings_by_use_type: str
    min_ratio_as_main_use: float

    @overload
    def __getattr__(self, item: Literal["buildings"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["filter_buildings_by_year_start"]) -> int | None: ...
    @overload
    def __getattr__(self, item: Literal["filter_buildings_by_year_end"]) -> int | None: ...
    @overload
    def __getattr__(self, item: Literal["filter_buildings_by_construction_type"]) -> str: ...
    @overload
    def __getattr__(self, item: Literal["filter_buildings_by_use_type"]) -> str: ...
    @overload
    def __getattr__(self, item: Literal["min_ratio_as_main_use"]) -> float: ...
    def __getattr__(self, item: str) -> Any: ...

class PlotsDemandSection(Section):
    """Typed section for plots-demand configuration"""
    y_metric_to_plot: list[str]
    y_metric_unit: Optional[str]
    y_normalised_by: Optional[str]
    x_to_plot: Optional[str]

    @overload
    def __getattr__(self, item: Literal["y_metric_to_plot"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["y_metric_unit"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["y_normalised_by"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["x_to_plot"]) -> Optional[str]: ...
    def __getattr__(self, item: str) -> Any: ...

class PlotsFinalEnergySection(Section):
    """Typed section for plots-final-energy configuration"""
    what_if_name: list[str]
    y_metric_to_plot: list[str]
    y_metric_unit: Optional[str]
    y_normalised_by: Optional[str]
    x_to_plot: Optional[str]

    @overload
    def __getattr__(self, item: Literal["what_if_name"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["y_metric_to_plot"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["y_metric_unit"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["y_normalised_by"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["x_to_plot"]) -> Optional[str]: ...
    def __getattr__(self, item: str) -> Any: ...

class PlotsHeatRejectionSection(Section):
    """Typed section for plots-heat-rejection configuration"""
    what_if_name: list[str]
    y_metric_to_plot: list[str]
    y_metric_unit: Optional[str]
    y_normalised_by: Optional[str]
    x_to_plot: Optional[str]

    @overload
    def __getattr__(self, item: Literal["what_if_name"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["y_metric_to_plot"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["y_metric_unit"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["y_normalised_by"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["x_to_plot"]) -> Optional[str]: ...
    def __getattr__(self, item: str) -> Any: ...

class PlotsLifecycleEmissionsSection(Section):
    """Typed section for plots-lifecycle-emissions configuration"""
    what_if_name: list[str]
    y_category_to_plot: list[str]
    operation_services: list[str]
    envelope_components: list[str]
    y_metric_unit: Optional[str]
    y_normalised_by: Optional[str]
    x_to_plot: Optional[str]

    @overload
    def __getattr__(self, item: Literal["what_if_name"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["y_category_to_plot"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["operation_services"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["envelope_components"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["y_metric_unit"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["y_normalised_by"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["x_to_plot"]) -> Optional[str]: ...
    def __getattr__(self, item: str) -> Any: ...

class PlotsOperationalEmissionsSection(Section):
    """Typed section for plots-operational-emissions configuration"""
    what_if_name: list[str]
    y_category_to_plot: Optional[str]
    operation_services: list[str] | None
    energy_carriers: list[str] | None
    y_metric_unit: Optional[str]
    y_normalised_by: Optional[str]
    x_to_plot: Optional[str]

    @overload
    def __getattr__(self, item: Literal["what_if_name"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["y_category_to_plot"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["operation_services"]) -> list[str] | None: ...
    @overload
    def __getattr__(self, item: Literal["energy_carriers"]) -> list[str] | None: ...
    @overload
    def __getattr__(self, item: Literal["y_metric_unit"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["y_normalised_by"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["x_to_plot"]) -> Optional[str]: ...
    def __getattr__(self, item: str) -> Any: ...

class PlotsEmissionTimelineSection(Section):
    """Typed section for plots-emission-timeline configuration"""
    what_if_name: list[str]
    plot_type: Optional[str]
    y_category_to_plot: list[str]
    operation_services: list[str]
    envelope_components: list[str]
    y_metric_unit: Optional[str]
    y_normalised_by: Optional[str]
    y_min: float | None
    y_max: float | None
    y_step: float | None
    net_zero_target_year: int
    context: dict[str, Any] | None

    @overload
    def __getattr__(self, item: Literal["what_if_name"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["plot_type"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["y_category_to_plot"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["operation_services"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["envelope_components"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["y_metric_unit"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["y_normalised_by"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["y_min"]) -> float | None: ...
    @overload
    def __getattr__(self, item: Literal["y_max"]) -> float | None: ...
    @overload
    def __getattr__(self, item: Literal["y_step"]) -> float | None: ...
    @overload
    def __getattr__(self, item: Literal["net_zero_target_year"]) -> int: ...
    @overload
    def __getattr__(self, item: Literal["context"]) -> dict[str, Any] | None: ...
    def __getattr__(self, item: str) -> Any: ...

class PlotsPathwayEmissionTimelineSection(Section):
    """Typed section for plots-pathway-emission-timeline configuration"""
    existing_pathway_names: list[str]
    plot_type: Optional[str]
    y_category_to_plot: list[str]
    operation_services: list[str]
    envelope_components: list[str]
    pv_code: str
    y_metric_unit: Optional[str]
    y_normalised_by: Optional[str]
    y_min: float | None
    y_max: float | None
    y_step: float | None
    net_zero_target_year: int
    cutoff_year: int | None
    context: dict[str, Any] | None

    @overload
    def __getattr__(self, item: Literal["existing_pathway_name"]) -> str: ...
    @overload
    def __getattr__(self, item: Literal["plot_type"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["y_category_to_plot"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["operation_services"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["envelope_components"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["pv_code"]) -> str: ...
    @overload
    def __getattr__(self, item: Literal["y_metric_unit"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["y_normalised_by"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["y_min"]) -> float | None: ...
    @overload
    def __getattr__(self, item: Literal["y_max"]) -> float | None: ...
    @overload
    def __getattr__(self, item: Literal["y_step"]) -> float | None: ...
    @overload
    def __getattr__(self, item: Literal["net_zero_target_year"]) -> int: ...
    @overload
    def __getattr__(self, item: Literal["cutoff_year"]) -> int | None: ...
    @overload
    def __getattr__(self, item: Literal["context"]) -> dict[str, Any] | None: ...
    def __getattr__(self, item: str) -> Any: ...

class PlotsSolarSection(Section):
    """Typed section for plots-solar configuration"""
    y_metric_to_plot: list[str]
    y_metric_unit: Optional[str]
    y_normalised_by: Optional[str]
    x_to_plot: Optional[str]

    @overload
    def __getattr__(self, item: Literal["y_metric_to_plot"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["y_metric_unit"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["y_normalised_by"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["x_to_plot"]) -> Optional[str]: ...
    def __getattr__(self, item: str) -> Any: ...

class PlotsCostBreakdownSection(Section):
    """Typed section for plots-cost-breakdown configuration"""
    what_if_name: list[str]
    y_category_to_plot: list[str]
    y_metric_unit: Optional[str]
    y_normalised_by: Optional[str]
    x_to_plot: Optional[str]

    @overload
    def __getattr__(self, item: Literal["what_if_name"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["y_category_to_plot"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["y_metric_unit"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["y_normalised_by"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["x_to_plot"]) -> Optional[str]: ...
    def __getattr__(self, item: str) -> Any: ...

class PlotsCostSankeySection(Section):
    """Typed section for plots-cost-sankey configuration"""
    plot_title: Any
    what_if_name: list[str]
    x_to_plot: list[str]
    y_category_to_plot: list[str]
    capex_view: Optional[str]
    y_metric_unit: Optional[str]
    y_normalised_by: Optional[str]

    @overload
    def __getattr__(self, item: Literal["plot_title"]) -> Any: ...
    @overload
    def __getattr__(self, item: Literal["what_if_name"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["x_to_plot"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["y_category_to_plot"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["capex_view"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["y_metric_unit"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["y_normalised_by"]) -> Optional[str]: ...
    def __getattr__(self, item: str) -> Any: ...

class PlotsEnergySankeySection(Section):
    """Typed section for plots-energy-sankey configuration"""
    plot_title: Any
    what_if_name: list[str]
    y_service_category_to_plot: list[str]
    y_metric_unit: Optional[str]
    use_solar_irradiation: bool

    @overload
    def __getattr__(self, item: Literal["plot_title"]) -> Any: ...
    @overload
    def __getattr__(self, item: Literal["what_if_name"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["y_service_category_to_plot"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["y_metric_unit"]) -> Optional[str]: ...
    @overload
    def __getattr__(self, item: Literal["use_solar_irradiation"]) -> bool: ...
    def __getattr__(self, item: str) -> Any: ...

class PlotsLdcComponentSection(Section):
    """Typed section for plots-ldc-component configuration"""
    what_if_name: list[str]
    scale: list[str]
    components: list[str] | None
    buildings: list[str] | None
    y_metric_unit: Optional[str]

    @overload
    def __getattr__(self, item: Literal["what_if_name"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["scale"]) -> list[str]: ...
    @overload
    def __getattr__(self, item: Literal["components"]) -> list[str] | None: ...
    @overload
    def __getattr__(self, item: Literal["buildings"]) -> list[str] | None: ...
    @overload
    def __getattr__(self, item: Literal["y_metric_unit"]) -> Optional[str]: ...
    def __getattr__(self, item: str) -> Any: ...

class Parameter:
    name: str
    section: Section
    fqname: str
    config: Configuration
    help: str
    category: Optional[str]
    nullable: bool

    def __init__(self, name: str, section: Section, config: Configuration) -> None: ...
    def __repr__(self) -> str: ...
    def decode(self, value: str) -> Any: ...
    def encode(self, value: Any) -> str: ...
    def get(self) -> Any: ...
    def get_raw(self) -> str: ...
    def replace_references(self, encoded_value: str) -> str: ...
    def set(self, value: Any) -> None: ...
    def set_empty(self) -> Any: ...

# Parameter type classes for better type hints
class BooleanParameter(Parameter): ...
class BuildingsParameter(Parameter): ...
class ChoiceParameter(Parameter): ...
class ChoiceParameterBase(Parameter): ...
class ColumnChoiceParameter(Parameter): ...
class ColumnMultiChoiceParameter(Parameter): ...
class ComponentMultiChoiceParameter(Parameter): ...
class CoordinateListParameter(Parameter): ...
class DatabasePathParameter(Parameter): ...
class DateParameter(Parameter): ...
class DistrictSupplyTypeParameter(Parameter): ...
class EnergyCarrierMultiChoiceParameter(Parameter): ...
class FileParameter(Parameter): ...
class GenerationParameter(Parameter): ...
class InputFileParameter(Parameter): ...
class IntegerParameter(Parameter): ...
class InterventionTemplateMultiChoiceParameter(Parameter): ...
class JsonParameter(Parameter): ...
class ListParameter(Parameter): ...
class MultiChoiceFeedstockParameter(Parameter): ...
class MultiChoiceParameter(Parameter): ...
class MultiSystemParameter(Parameter): ...
class NetworkLayoutChoiceParameter(Parameter): ...
class NetworkLayoutMultiChoiceParameter(Parameter): ...
class NetworkLayoutNameParameter(Parameter): ...
class NullablePathParameter(Parameter): ...
class OptimizationIndividualListParameter(Parameter): ...
class OrderedMultiChoiceParameter(Parameter): ...
class PathParameter(Parameter): ...
class PhasingPlanChoiceParameter(Parameter): ...
class PlantNodeParameter(Parameter): ...
class PlotContextParameter(Parameter): ...
class PluginListParameter(Parameter): ...
class RealParameter(Parameter): ...
class ResumeFileParameter(Parameter): ...
class ScenarioNameMultiChoiceParameter(Parameter): ...
class ScenarioNameParameter(Parameter): ...
class ScenarioParameter(Parameter): ...
class SingleBuildingParameter(Parameter): ...
class SingleThermalStorageParameter(Parameter): ...
class SolarPanelChoiceParameter(Parameter): ...
class SolarPanelMultiChoiceParameter(Parameter): ...
class StandardMultiChoiceParameter(Parameter): ...
class StringParameter(Parameter): ...
class SubfolderChoiceParameter(Parameter): ...
class SubfoldersParameter(Parameter): ...
class SystemParameter(Parameter): ...
class UseTypeRatioParameter(Parameter): ...
class UserNetworkInputFileParameter(Parameter): ...
class WeatherPathParameter(Parameter): ...
class WhatIfNameChoiceParameter(Parameter): ...
class WhatIfNameMultiChoiceParameter(Parameter): ...
class WhatIfNameParameter(Parameter): ...
class WorkflowParameter(Parameter): ...

def config_identifier(python_identifier: str) -> str: ...
