name: Ruff
on:
  pull_request:
  push:
    branches: [ master ]
    paths: ['cea/**']

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Ruff Linter
        uses: astral-sh/ruff-action@v2
        with:
          src: ./cea
